name: Latest blog post BR activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog-br:
    name: Update this repo's README with latest activity from ptBR blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-BR"
          commit_message: "Updated readme with the latest ptBR blog data"
          feed_list: "https://feeds.feedburner.com/Brdevlawyer"
